### ISSUE TITLE
Identificar y describir interesados

### ISSUE THREAD

**Issue by WillianOrozco** [WillianOrozco/equipo7_dem_ppi2020#10]

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1rnji8j4bXt4tKWb5bfVVlOpP3cQDjgnG/view?usp=sharing

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1rnji8j4bXt4tKWb5bfVVlOpP3cQDjgnG/view?usp=sharing
