### ISSUE TITLE
Declarar la situación problema

### ISSUE THREAD

**Issue by WillianOrozco** [WillianOrozco/equipo7_dem_ppi2020#11]

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1_UhYf3Nxe6Hq0OcGSR18DRykYepeNPh0/view?usp=sharing

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1_UhYf3Nxe6Hq0OcGSR18DRykYepeNPh0/view?usp=sharing

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1_UhYf3Nxe6Hq0OcGSR18DRykYepeNPh0/view?usp=sharing

**Comment by Juliandbf-14** [comment]
https://drive.google.com/file/d/1rO3xMQCb4GrSFK6X45xIyR8pU3IhAoQZ/view?usp=sharing
